"""initial schema

Revision ID: 8cc500a39a55
Revises: 
Create Date: 2026-09-14 10:49:25.564948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8cc500a39a55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lon', sa.Float(), nullable=True),
    sa.Column('last_satellites', sa.Integer(), nullable=True),
    sa.Column('last_uptime_s', sa.Integer(), nullable=True),
    sa.Column('last_rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('device_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('satellites', sa.Integer(), nullable=True),
    sa.Column('uptime_s', sa.Integer(), nullable=True),
    sa.Column('free_heap', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('battery_v', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_heartbeats_at'), 'device_heartbeats', ['at'], unique=False)
    op.create_index(op.f('ix_device_heartbeats_device_id'), 'device_heartbeats', ['device_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_device_id'), 'emergency_contacts', ['device_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity_class', sa.Integer(), nullable=True),
    sa.Column('severity_name', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('p_crash', sa.Float(), nullable=True),
    sa.Column('model_severity', sa.String(length=16), nullable=True),
    sa.Column('accident_confirmed', sa.Boolean(), nullable=True),
    sa.Column('probabilities', sa.JSON(), nullable=True),
    sa.Column('peak_g', sa.Float(), nullable=True),
    sa.Column('excursion_ms', sa.Float(), nullable=True),
    sa.Column('impulse_gs', sa.Float(), nullable=True),
    sa.Column('signature_match', sa.Boolean(), nullable=True),
    sa.Column('label_source', sa.String(length=32), nullable=True),
    sa.Column('unit_scale_applied', sa.Float(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('classification_pending', sa.Boolean(), nullable=False),
    sa.Column('trigger_peak_g', sa.Float(), nullable=True),
    sa.Column('trigger_jerk_gs', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('gps_valid', sa.Boolean(), nullable=True),
    sa.Column('satellites', sa.Integer(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_accident_confirmed'), 'incidents', ['accident_confirmed'], unique=False)
    op.create_index(op.f('ix_incidents_classification_pending'), 'incidents', ['classification_pending'], unique=False)
    op.create_index(op.f('ix_incidents_device_id'), 'incidents', ['device_id'], unique=False)
    op.create_index(op.f('ix_incidents_event_id'), 'incidents', ['event_id'], unique=True)
    op.create_index(op.f('ix_incidents_label_source'), 'incidents', ['label_source'], unique=False)
    op.create_index(op.f('ix_incidents_received_at'), 'incidents', ['received_at'], unique=False)
    op.create_index('ix_incidents_received_severity', 'incidents', ['received_at', 'severity_class'], unique=False)
    op.create_index(op.f('ix_incidents_severity_class'), 'incidents', ['severity_class'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('dispatch_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_events_incident_id'), 'dispatch_events', ['incident_id'], unique=False)
    op.create_table('incident_windows',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('fs_hz', sa.Integer(), nullable=False),
    sa.Column('ax', sa.JSON(), nullable=False),
    sa.Column('ay', sa.JSON(), nullable=False),
    sa.Column('az', sa.JSON(), nullable=False),
    sa.Column('gx', sa.JSON(), nullable=False),
    sa.Column('gy', sa.JSON(), nullable=False),
    sa.Column('gz', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_windows')
    op.drop_index(op.f('ix_dispatch_events_incident_id'), table_name='dispatch_events')
    op.drop_table('dispatch_events')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity_class'), table_name='incidents')
    op.drop_index('ix_incidents_received_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_received_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_label_source'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_event_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_device_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_classification_pending'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_accident_confirmed'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_emergency_contacts_device_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_device_heartbeats_device_id'), table_name='device_heartbeats')
    op.drop_index(op.f('ix_device_heartbeats_at'), table_name='device_heartbeats')
    op.drop_table('device_heartbeats')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
