"""session cutoff for password changes

Revision ID: bf2d51828375
Revises: 03e0c9003e83
Create Date: 2026-09-15 20:06:33.018106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf2d51828375'
down_revision: Union[str, None] = '03e0c9003e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Added nullable, backfilled, then made NOT NULL: existing rows have no
    # value, and SQLite cannot add a NOT NULL column with a non-constant
    # default. Backfilling to the epoch keeps every current session valid —
    # a schema change should not sign everyone out.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE users SET sessions_valid_from = '1970-01-01 00:00:00+00:00'")
    with op.batch_alter_table('users') as batch:
        batch.alter_column('sessions_valid_from',
                           existing_type=sa.DateTime(timezone=True),
                           nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch:
        batch.drop_column('sessions_valid_from')
    # ### end Alembic commands ###
