"""add response units

Revision ID: f48afd8ee6fb
Revises: 8cc500a39a55
Create Date: 2026-09-14 12:29:19.241902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f48afd8ee6fb'
down_revision: Union[str, None] = '8cc500a39a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_sign', sa.String(length=32), nullable=False),
    sa.Column('unit_type', sa.String(length=16), nullable=False),
    sa.Column('station_name', sa.String(length=128), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=False),
    sa.Column('home_lon', sa.Float(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('assigned_incident_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_units_assigned_incident_id'), 'response_units', ['assigned_incident_id'], unique=False)
    op.create_index(op.f('ix_response_units_call_sign'), 'response_units', ['call_sign'], unique=True)
    op.create_index(op.f('ix_response_units_status'), 'response_units', ['status'], unique=False)
    op.create_index(op.f('ix_response_units_unit_type'), 'response_units', ['unit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_units_unit_type'), table_name='response_units')
    op.drop_index(op.f('ix_response_units_status'), table_name='response_units')
    op.drop_index(op.f('ix_response_units_call_sign'), table_name='response_units')
    op.drop_index(op.f('ix_response_units_assigned_incident_id'), table_name='response_units')
    op.drop_table('response_units')
    # ### end Alembic commands ###
